### ISSUE TITLE
Error in log file on rename

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/docker-pubchem#63]
Maybe it is because of the first import.

```
import_1   | 2022-08-09T08:31:50.046Z syncNpAtlases Processing: counter: 32270 - imported: 32269
import_1   | 2022-08-09T08:31:56.216Z syncNpAtlases collection not found to rename
import_1   | 2022-08-09T08:31:56.218Z cron Closing connection
import_1   | /git/pubchem/node_modules/mongodb/lib/utils.js:369
import_1   |     throw new error_1.MongoNotConnectedError('MongoClient must be connected to perform this operation');
import_1   |           ^
import_1   | 
import_1   | MongoNotConnectedError: MongoClient must be connected to perform this operation
import_1   |     at getTopology (/git/pubchem/node_modules/mongodb/lib/utils.js:369:11)
import_1   |     at Collection.find (/git/pubchem/node_modules/mongodb/lib/collection.js:242:69)
import_1   |     at PubChemConnection.getProgress (file:///git/pubchem/src/utils/PubChemConnection.js:85:40)
import_1   |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
import_1   |     at async logInDB (file:///git/pubchem/src/utils/Debug.js:44:20)
import_1   | 
import_1   | Node.js v18.6.0
import_1   | 
import_1   | > node-pubchem@1.0.0 cron
import_1   | > DEBUG=* node -r dotenv/config src/sync/cron
import_1   | 

```

**Comment by RicardoSilvestr** [comment]
solved
